on:
  workflow_call:
    inputs:
      sonarOrganization:
        required: true
        type: string
      sonarProjectKey:
        required: true
        type: string
      dockerImage:
        required: true
        type: string
      dockerUsername:
        required: true
        type: string
      eventType:
        required: true
        type: string
    secrets:
      sonar-token:
        required: true
      docker-token:
        required: true
      repo-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b #v4.5.0
        with:
          java-version: 17

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco verify

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ inputs.sonarOrganization }}
          -Dsonar.projectKey=${{ inputs.sonarProjectKey }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: Build Docker image - Main
        if: github.ref == 'refs/heads/main'
        run: >
          mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
          -Djib.httpTimeout=60000
          -Djib.to.image=${{ inputs.dockerImage }}
          -Djib.to.auth.username=${{ inputs.dockerUsername }}
          -Djib.to.auth.password=${{ secrets.docker-token }}

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@main
        with:
          token: ${{ secrets.repo-token }}
          event-type: ${{ inputs.eventType }}
