on:
  workflow_call:
    inputs:
      sonarOrganization:
        required: true
        type: string
      sonarProjectKey:
        required: true
        type: string
      eventOrganizations:
        required: false
        default: ''
        type: string
      eventType:
        required: true
        type: string
    secrets:
      sonar-token:
        required: true
      repo-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1 v1.4.4
        with:
          java-version: 21

      - name: Checkout sources
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1 v1.2.0

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco verify

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization="$RUNGHA_SONAR_ORGANIZATION"
          -Dsonar.projectKey="$RUNGHA_SONAR_PROJECT_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          RUNGHA_SONAR_ORGANIZATION: ${{ inputs.sonarOrganization }} # just for defense against script injection
          RUNGHA_SONAR_PROJECT_KEY: ${{ inputs.sonarProjectKey }} # just for defense against script injection

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@67201bc793618876822097ce2152b23b496a8227 # main
        with:
          token: ${{ secrets.repo-token }}
          organizations: ${{ inputs.eventOrganizations }}
          event-type: ${{ inputs.eventType }}
