on:
  workflow_call:
    inputs:
      dockerImage:
        required: true
        type: string
      dockerUsername:
        description: 'Used to write latest images after the PR is merged in main'
        required: true
        type: string
      dockerRoUsername:
        description: 'Used to read the images (FROM: clause in the Dockerfile) to test the Dockerfile in the PR'
        required: true
        type: string
      eventOrganizations:
        required: false
        default: ''
        type: string
      eventType:
        required: true
        type: string
      environment:
        required: false
        default: 'release'
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      docker-ro-token:
        required: true
      repo-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && inputs.environment || '' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
        with:
          name: ${{ inputs.dockerImage }}
          username: ${{ github.ref != 'refs/heads/main' && inputs.dockerRoUsername || inputs.dockerUsername }}
          password: ${{ github.ref != 'refs/heads/main' && secrets.docker-ro-token || secrets.DOCKERHUB_TOKEN }}
          no_push: ${{ github.ref != 'refs/heads/main' }}
          tags: "latest"

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@main
        with:
          token: ${{ secrets.repo-token }}
          organizations: ${{ inputs.eventOrganizations }}
          event-type: ${{ inputs.eventType }}
