on:
  workflow_call:
    inputs:
      githubappId:
        required: true
        type: string
      dockerImage:
        required: true
        type: string
      dockerUsername:
        required: true
        type: string
      releaseVersion:
        required: true
        type: string
      environment:
        required: false
        default: 'release'
        type: string
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  patch:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        name: Generate app token
        with:
          app-id: ${{ inputs.githubappId }}
          private-key: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Parse release version
        run: |
          regex="^v([0-9]+)\.([0-9]+)$"
          if [[ ${{ inputs.releaseVersion }} =~ $regex ]]
          then
            echo Release version matches vX.X format
          else 
            echo ERROR: release version should match the format vX.X
            exit 1
          fi

      - name: Check if release already exists
        run: |
          if git ls-remote --quiet --exit-code origin refs/heads/release-${{ inputs.releaseVersion }} >/dev/null 2>&1
          then
            echo "Release ${{ inputs.releaseVersion }} already exists, patch will be perfomed"
          else
            echo "Release ${{ inputs.releaseVersion }} doesn't exist, patch cannot be performed"
            exit 1
          fi

      - name: Checkout on existing release branch
        run: |
          git checkout release-${{ inputs.releaseVersion }}

      - name: Extract tag versions
        run: |
          lastTag=$(git describe --tags --abbrev=0)
          regex="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
          if [[ $lastTag =~ $regex ]]
          then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            ((++patch))
            echo "GITHUB_MAJOR_VERSION=$major" >> $GITHUB_ENV
            echo "GITHUB_MINOR_VERSION=$minor" >> $GITHUB_ENV
            echo "GITHUB_PATCH_VERSION=$patch" >> $GITHUB_ENV
            echo "GITHUB_SHORT_VERSION=$major.$minor.$patch" >> $GITHUB_ENV
          else
            echo "ERROR: last tag $lastTag does not match required format vX.X.X"
            exit 1
          fi

      - name: Create tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag v${{ env.GITHUB_SHORT_VERSION }}

      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
        with:
          name: ${{ inputs.dockerImage }}
          username: ${{ inputs.dockerUsername }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{ env.GITHUB_SHORT_VERSION }}

      - name: Push release branch and tag
        run: |
          git push origin v${{ env.GITHUB_SHORT_VERSION }}          
