on:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version (format: vX.X)'
        required: true
        type: string
      commitSha:
        description: 'SHA of the commit to release from'
        required: true
        type: string
      dockerImage:
        description: 'Name of the Docker image (e.g., organization/app-name)'
        required: true
        type: string
      dockerUsername:
        required: true
        type: string
      githubappId:
        description: 'GitHub App ID for authentication'
        required: true
        type: string
    secrets:
      githubappPrivateKey:
        required: true
      docker-token:
        required: true
      sonar-token:
        required: true

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.githubappId }}
          private-key: ${{ secrets.githubappPrivateKey }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract Version Numbers
        run: |
          if ! [[ ${{ inputs.releaseVersion }} =~ ^v([0-9]+)\.([0-9]+)$ ]]; then
            echo "Error: Invalid version format. Must be vX.X (e.g., v1.2)"
            exit 1
          fi
          
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          
          echo "RELEASE_MAJOR_VERSION=${MAJOR}" >> $GITHUB_ENV
          echo "RELEASE_MINOR_VERSION=${MINOR}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${MAJOR}.${MINOR}.0" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=release-v${MAJOR}.${MINOR}" >> $GITHUB_ENV

      - name: Create Release Branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH }} ${{ inputs.commitSha }}

      - name: Update Version and Tag
        run: |
          # Configure git for commits
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Use npm version to update version, create commit and tag
          npm version ${{ env.RELEASE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Quality Checks
        run: |
          npm run lint
          npm run test:coverage
          npm run licenses-check

      - name: Build Application
        run: npm run build

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
        with:
          name: ${{ inputs.dockerImage }}
          username: ${{ inputs.dockerUsername }}
          password: ${{ secrets.docker-token }}
          tags: ${{ env.RELEASE_VERSION }}

      - name: Push release branch and tag
        run: |
          git push origin ${{ env.RELEASE_BRANCH }}
          git push origin v${{ env.RELEASE_VERSION }}

      - name: Checkout main
        run: |
          git checkout main
          git pull

      - name: Get current package version
        run: |
          echo "CURRENT_NPM_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Extract current version
        run: |
          regex="(.*)-SNAPSHOT"
          if [[ ${{ env.CURRENT_NPM_VERSION }} =~ $regex ]]; 
          then
            echo "CURRENT_RELEASE_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          fi

      - name: Update SNAPSHOT version on main
        if: env.CURRENT_RELEASE_VERSION == env.RELEASE_VERSION
        run: |
          # Calculate next development version
          NEW_MINOR=$((RELEASE_MINOR_VERSION + 1))
          DEV_VERSION="${RELEASE_MAJOR_VERSION}.${NEW_MINOR}.0-SNAPSHOT"
          
          # Update package.json with development version
          npm version ${DEV_VERSION} --no-git-tag-version
          
          # Commit and push changes
          git add .
          git commit -m "Bump version to v${DEV_VERSION}"
          git push origin main