on:
  workflow_call:
    inputs:
      githubappId:
        required: true
        type: string
      sonarOrganization:
        required: true
        type: string
      sonarProjectKey:
        required: true
        type: string
      dockerImage:
        required: true
        type: string
      dockerUsername:
        required: true
        type: string
      releaseVersion:
        required: true
        type: string
      gitReference:
        required: true
        type: string
      force-release:
        required: false
        type: boolean
        default: false
    secrets:
      githubappPrivateKey:
        required: true
      sonar-token:
        required: true
      docker-token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        name: Generate app token
        with:
          app-id: ${{ inputs.githubappId }}
          private-key: ${{ secrets.githubappPrivateKey }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Parse release version
        run: |
          regex="^v([0-9]+)\.([0-9]+)$"
          if [[ ${{ inputs.releaseVersion }} =~ $regex ]]
          then
            echo "GITHUB_MAJOR_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "GITHUB_MINOR_VERSION=${BASH_REMATCH[2]}" >> $GITHUB_ENV
            echo "GITHUB_SHORT_VERSION=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.0" >> $GITHUB_ENV
          else 
            echo ERROR: release version should match the format vX.X
            exit 1
          fi

      - name: Check and handle existing release
        run: |
          BRANCH_EXISTS=$(git ls-remote --quiet --exit-code origin refs/heads/release-${{ inputs.releaseVersion }} >/dev/null 2>&1; echo $?)
          TAG_EXISTS=$(git ls-remote --quiet --exit-code origin refs/tags/v${{ env.GITHUB_SHORT_VERSION }} >/dev/null 2>&1; echo $?)
          
          if [ $BRANCH_EXISTS -eq 0 ] || [ $TAG_EXISTS -eq 0 ]; then
            if [[ "${{ inputs.force-release }}" != "true" ]]; then
              echo "ERROR: Release ${{ inputs.releaseVersion }} already exists. Use force-release: true to override"
              exit 1
            else
              echo "Force release enabled - cleaning up existing release artifacts"
          
              # Delete remote branch if it exists
              if [ $BRANCH_EXISTS -eq 0 ]; then
                git push origin --delete release-${{ inputs.releaseVersion }}
                echo "Deleted existing release branch"
              fi
          
              # Delete remote tag if it exists
              if [ $TAG_EXISTS -eq 0 ]; then
                git push origin --delete v${{ env.GITHUB_SHORT_VERSION }}
                echo "Deleted existing release tag"
              fi
            fi
          fi
          echo "Proceeding with release creation"

      - name: Checkout with new branch
        run: |
          git checkout -b release-v${{ env.GITHUB_MAJOR_VERSION }}.${{ env.GITHUB_MINOR_VERSION }} ${{ inputs.gitReference }}

      - name: Change Maven version to release version
        run: mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ env.GITHUB_SHORT_VERSION }}

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco verify

      - name: Commit and tag release version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release v${{ env.GITHUB_SHORT_VERSION }}"
          git tag v${{ env.GITHUB_SHORT_VERSION }}
          git push origin release-v${{ env.GITHUB_MAJOR_VERSION }}.${{ env.GITHUB_MINOR_VERSION }}
          git push origin v${{ env.GITHUB_SHORT_VERSION }}

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ inputs.sonarOrganization }}
          -Dsonar.projectKey=${{ inputs.sonarProjectKey }}
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: Build Docker image
        run: >
          mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
          -Djib.httpTimeout=60000
          -Djib.to.image=${{ inputs.dockerImage }}:${{ env.GITHUB_SHORT_VERSION }}
          -Djib.to.auth.username=${{ inputs.dockerUsername }}
          -Djib.to.auth.password=${{ secrets.docker-token }}

      - name: Checkout main
        run: |
          git checkout main
          git pull

      - name: Get current maven version
        run: |
          echo "CURRENT_MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Extract current version
        run: |
          regex="(.*)-SNAPSHOT"
          if [[ ${{ env.CURRENT_MAVEN_VERSION }} =~ $regex ]]
          then
            echo "CURRENT_RELEASE_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          fi

      - name: Update SNAPSHOT version on main
        if: env.CURRENT_RELEASE_VERSION == env.GITHUB_SHORT_VERSION
        run: |
          minor=${{ env.GITHUB_MINOR_VERSION }}
          ((++minor))
          mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ env.GITHUB_MAJOR_VERSION }}.$minor.0-SNAPSHOT
          git add .
          git commit -m "Update SNAPSHOT version to v${{ env.GITHUB_MAJOR_VERSION }}.$minor.0"
          git push
