on:
  workflow_call:
    inputs:
      githubappId:
        required: true
        type: string
      versionType:
        description: 'Version type increment (major | minor)'
        required: true
        type: string
      environment:
        required: false
        default: 'release'
        type: string
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      # don't allow to disable this check, and for security only succeed if everything goes perfectly and outputs "true"
      # TODO deduplicate this code when github actions allows to easily share a script used
      # by reusable workflows. Currently only the workflow file is checked out at the caller
      # There are no good workarounds to checkout a companion file (script or composite action)
      - name: Check Actor Permission
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "checking permission=maintain on repo=$GITHUB_REPOSITORY for user=$GITHUB_ACTOR"
          # no need to escape GITHUB_REPOSITORY and GITHUB_ACTOR because github
          # names can only contain ASCII letters, digits, and the characters ., # -, and _.
          # permission: legacy, is actually a role (one per user) and doesn't
          #   have "maintain" role, only ["none", "read", "write", "admin"]
          # role_name: one per user, new standard roles, custom roles, "" and
          #   "push" and "pull" instead of "none" and "read" and "write": "",
          #   "read", "triage", "write", "maintain", "admin" and also non
          #   standard custom roles
          # user.permissions: boolean status only for each standard permissions "pull", "triage", "push", "maintain", "admin"
          # So the best for now is to use user.permissions I think.
          # NOTE: the gh api returns a JSON boolean so jq can only output true or false without quotes
          # (actually even for JSON strings gh's gojq implementation strips the quotes by default unlike jq)
          allowed=$(gh api "repos/$GITHUB_REPOSITORY/collaborators/$GITHUB_ACTOR/permission" --jq '.user.permissions["maintain"]')
          [[ "$allowed" == "true" ]] || exit 1

      - name: Validate Version Type
        run: |
          if [[ ! "${{ inputs.versionType }}" =~ ^(major|minor)$ ]]; then
            echo "Error: versionType must be one of: major, minor"
            echo "Received: ${{ inputs.versionType }}"
            exit 1
          fi

      # TODO make a composite action for the next steps to setup git (unless create-github-app-token incorporates all this...)
      # Copied from create-github-app-token README "Configure git CLI for an app's bot user"
      - uses: actions/create-github-app-token@v1
        id: app-token
        name: Generate app token
        with:
          app-id: ${{ inputs.githubappId }}
          private-key: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Setup git user
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Calculate versions
        id: versions
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          LATEST_VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
          
          case "${{ inputs.versionType }}" in
            "major")
              RELEASE_VERSION="$((MAJOR + 1)).0.0"
              NEXT_VERSION="$((MAJOR + 1)).1.0-SNAPSHOT"
              ;;
            "minor")
              RELEASE_VERSION="$MAJOR.$((MINOR + 1)).0"
              NEXT_VERSION="$MAJOR.$((MINOR + 2)).0-SNAPSHOT"
              ;;
          esac
          
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_OUTPUT
          echo "Release version will be: ${RELEASE_VERSION}"
          echo "Next development version will be: ${NEXT_VERSION}"

      - name: Set release version
        run: |
          mvn versions:set -DnewVersion=${{ steps.versions.outputs.RELEASE_VERSION }} -DgenerateBackupPoms=false
          git commit -am "Release v${{ steps.versions.outputs.RELEASE_VERSION }}"

      - name: Create and push tag
        run: |
          git tag v${{ steps.versions.outputs.RELEASE_VERSION }}
          git push origin v${{ steps.versions.outputs.RELEASE_VERSION }}

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release create v${{ steps.versions.outputs.RELEASE_VERSION }} \
            --title "v${{ steps.versions.outputs.RELEASE_VERSION }}" \
            --generate-notes

      - name: Set next development version
        run: |
          mvn versions:set -DnewVersion=${{ steps.versions.outputs.NEXT_VERSION }} -DgenerateBackupPoms=false
          git commit -am "Update SNAPSHOT version to v${{ steps.versions.outputs.NEXT_VERSION }}"
          git push origin main